import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const css=await readFile(new URL('../dist/tokens.css',import.meta.url),'utf8');
const values=Object.fromEntries([...css.matchAll(/--([a-z0-9-]+):\s*(#[0-9a-f]{3,6})/g)].map(m=>[m[1],m[2]]));
const rgb=hex=>{let h=hex.slice(1);if(h.length===3)h=[...h].map(x=>x+x).join('');return [0,2,4].map(i=>parseInt(h.slice(i,i+2),16)/255);};
const lum=h=>rgb(h).map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4).reduce((s,c,i)=>s+c*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>{const x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);};
test('Texto normal y estados superan contraste 4.5:1',()=>{for(const [fg,bg]of [['text-color-text-primary','background-color-background-primary'],['text-color-text-secondary','background-color-background-secondary'],['status-publicada-foreground','status-publicada-background'],['text-color-text-primary','status-adjudicada-background'],['text-color-text-primary','status-warning-background'],['status-warning-foreground','background-color-background-primary'],['status-error-foreground','status-error-background'],['brand-700','brand-50']])assert.ok(contrast(values[fg],values[bg])>=4.5,`${fg} sobre ${bg}`);});
test('Bordes de control y foco superan contraste no textual 3:1',()=>{for(const token of ['status-neutral-border','brand-700'])assert.ok(contrast(values[token],values['background-color-background-primary'])>=3);});
test('Estructura incluye idioma, destino de salto, etiquetas y modales nativos',async()=>{const html=await readFile(new URL('../dist/index.html',import.meta.url),'utf8');assert.match(html,/<html lang="es-CL">/);assert.match(html,/href="#contenido"/);assert.match(html,/id="contenido" tabindex="-1"/);assert.equal((html.match(/<dialog /g)||[]).length,2);assert.match(html,/aria-live="polite"/);for(const id of ['search','region','status','from','to','sheet-region','sheet-status','sheet-from','sheet-to','mobile-order','desktop-order'])assert.ok(html.includes(`for="${id}"`),`Etiqueta ${id}`);assert.match(html,/name="viewport"/);});
